### ISSUE TITLE
Missing rogue/hardware/data/DataMap.h

### ISSUE THREAD

**Issue by HGrabas** [slaclab/rogue#112]
Inside DataMap.cpp
#include <rogue/hardware/data/DataMap.h>

File DataMap.h is missing from the repo.

**Comment by ruck314** [comment]
https://jira.slac.stanford.edu/browse/ESROGUE-126

**Comment by slacrherbst** [comment]
The file is present in the repo and I don't see any errors when building the master branch:
https://github.com/slaclab/rogue/blob/master/include/rogue/hardware/data/DataMap.h
