### ISSUE TITLE
Memory leak in ris::Pool

### ISSUE THREAD

**Issue by PrimozLavric** [slaclab/rogue#861]
Buffers that are stored on the buffer queue (`dataQ_`) are never freed:
https://github.com/slaclab/rogue/blob/main/src/rogue/interfaces/stream/Pool.cpp#L87

Proposed fix:
```
ris::Pool::~Pool()
{
   while (!dataQ_.empty())
   {
      free(dataQ_.front());
      dataQ_.pop();
   }
}
```

**Comment by bengineerd** [comment]
Resolved in #861
