### ISSUE TITLE
RSSI Controller std::thread memory leak

### ISSUE THREAD

**Issue by PrimozLavric** [slaclab/rogue#862]
In `rpr::Controller::start` a thread is created using new, but never freed:
https://github.com/slaclab/rogue/blob/main/src/rogue/protocols/rssi/Controller.cpp#L146

Proposed fix:
Add `delete thread_` to `rpr::Controller::stop` or better avoid creating a thread using `new`.

**Comment by bengineerd** [comment]
I created https://github.com/slaclab/rogue/pull/866 to fix this.

Thank you for these reports. We appreciate contributions from external collaborators.

**Comment by bengineerd** [comment]
Resolved in #866.
