### ISSUE TITLE
UDP Server and Client internal thread may cause std::bad_weak_ptr exception to be thrown

### ISSUE THREAD

**Issue by PrimozLavric** [slaclab/rogue#863]
shared_from_this() may be called before the object and shared_ptr are fully initialized. This causes std::bad_weak_ptr exception and crashes the application.

Trace Server:
[rpu::Server::runThread()](https://github.com/slaclab/rogue/blob/main/src/rogue/protocols/udp/Server.cpp#L87)
-- [ris::Pool::acceptReq(maxPayload(),false)](https://github.com/slaclab/rogue/blob/main/src/rogue/protocols/udp/Server.cpp#L190)
---- [allocBuffer(size,&frSize)](https://github.com/slaclab/rogue/blob/main/src/rogue/interfaces/stream/Pool.cpp#L74)
------ [shared_from_this()](https://github.com/slaclab/rogue/blob/main/src/rogue/interfaces/stream/Pool.cpp#L166)

Trace Client:
[rpu::Client::runThread()](https://github.com/slaclab/rogue/blob/main/src/rogue/protocols/udp/Client.cpp#L90)
-- [ris::Pool::acceptReq(maxPayload(),false)](https://github.com/slaclab/rogue/blob/main/src/rogue/protocols/udp/Client.cpp#L186)
---- [allocBuffer(size,&frSize)](https://github.com/slaclab/rogue/blob/main/src/rogue/interfaces/stream/Pool.cpp#L74)
------ [shared_from_this()](https://github.com/slaclab/rogue/blob/main/src/rogue/interfaces/stream/Pool.cpp#L166)

Proposed fix:
```
auto weakPtr = weak_from_this();
auto sharedPtr = weakPtr.lock();

while (!sharedPtr) {
    std::this_thread::yield();
    sharedPtr = weakPtr.lock();
}
```

**Comment by bengineerd** [comment]
This might have been fixed by https://github.com/slaclab/rogue/pull/836

**Comment by PrimozLavric** [comment]
Yes, that indeed fixes the issue.
